name: qylon-production
region: nyc3

services:
  - name: api-gateway
    source_dir: services/api-gateway
    github:
      repo: KD-Squares/qylon
      branch: main
    build_command: cd services/api-gateway && npm ci && npm run build
    run_command: cd services/api-gateway && npm start
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 8080
    routes:
      - path: /api
    envs:
      - key: NODE_ENV
        value: production
        scope: RUN_TIME
      - key: PORT
        value: '8080'
        scope: RUN_TIME
      - key: JWT_SECRET
        value: ${JWT_SECRET}
        scope: RUN_TIME
      - key: SUPABASE_URL
        value: ${SUPABASE_URL}
        scope: RUN_TIME
      - key: SUPABASE_SERVICE_ROLE_KEY
        value: ${SUPABASE_SERVICE_ROLE_KEY}
        scope: RUN_TIME
      - key: SUPABASE_ANON_KEY
        value: ${SUPABASE_ANON_KEY}
        scope: RUN_TIME
      - key: OPENAI_API_KEY
        value: ${OPENAI_API_KEY}
        scope: RUN_TIME
      - key: RECALL_AI_API_KEY
        value: ${RECALL_AI_API_KEY}
        scope: RUN_TIME
      - key: CORS_ORIGIN
        value: ${CORS_ORIGIN}
        scope: RUN_TIME
    health_check:
      http_path: /health
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3

static_sites:
  - name: frontend
    source_dir: frontend
    github:
      repo: KD-Squares/qylon
      branch: main
    build_command: cd frontend && npm ci && npm run build
    output_dir: frontend/dist
    index_document: index.html
    error_document: index.html
    catchall_document: index.html
    routes:
      - path: /
    envs:
      - key: VITE_SUPABASE_URL
        value: ${SUPABASE_URL}
        scope: BUILD_TIME
      - key: VITE_SUPABASE_ANON_KEY
        value: ${SUPABASE_ANON_KEY}
        scope: BUILD_TIME
      - key: VITE_API_URL
        value: https://qylon-app-f7utg.ondigitalocean.app/api
        scope: BUILD_TIME

domains:
  - domain: qylon.ai
    type: PRIMARY
  - domain: www.qylon.ai
    type: ALIAS