version: '3.8'

services:
  # API Gateway
  api-gateway:
    build:
      context: ./services/api-gateway
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - PORT=3000
      - CORS_ORIGIN=http://localhost:3000
      - JWT_SECRET=${JWT_SECRET:-ci-test-jwt-secret-key-for-testing-only}
      - REDIS_URL=redis://localhost:16379
      - SUPABASE_URL=${SUPABASE_URL:-https://placeholder.supabase.co}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY:-placeholder-anon-key}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY:-placeholder-service-role-key}
    networks:
      - qylon-network

  # Integration Management Service
  integration-management:
    build:
      context: ./services/integration-management
      dockerfile: Dockerfile
    ports:
      - '3006:3006'
    environment:
      - NODE_ENV=development
      - PORT=3006
      - DATABASE_URL=postgresql://postgres:postgres@localhost:15432/qylon_test
      - REDIS_URL=redis://localhost:16379
      - SUPABASE_URL=${SUPABASE_URL:-https://placeholder.supabase.co}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY:-placeholder-service-role-key}
      - JWT_SECRET=${JWT_SECRET:-ci-test-jwt-secret-key-for-testing-only}
    networks:
      - qylon-network

networks:
  qylon-network:
    driver: bridge
