
[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "integration-managemet1-service"
version = "0.1.0"
description = "Qylon Integration Management Service 1"
