name: Fix Resource Limits

on:
  workflow_dispatch:
  # Only run when manually triggered or when specific files change
  # push:
  #   branches: [main]
  #   paths:
  #     - '.do/app-resource-fixed.yaml'
  #     - 'scripts/fix-resource-limits.sh'

jobs:
  fix-resources:
    name: Fix DigitalOcean Resource Limits
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install DigitalOcean CLI
        run: |
          wget https://github.com/digitalocean/doctl/releases/download/v1.101.0/doctl-1.101.0-linux-amd64.tar.gz
          tar xf doctl-1.101.0-linux-amd64.tar.gz
          sudo mv doctl /usr/local/bin
          doctl version

      - name: Fix Resource Limits
        env:
          DO_ACCESS_TOKEN: ${{ secrets.DO_ACCESS_TOKEN }}
          DO_APP_ID: ${{ secrets.DO_APP_ID }}
        run: |
          chmod +x scripts/fix-resource-limits.sh
          ./scripts/fix-resource-limits.sh

      - name: Wait for deployment
        run: |
          echo "Waiting 60 seconds for deployment to start..."
          sleep 60

      - name: Check deployment status
        env:
          DO_ACCESS_TOKEN: ${{ secrets.DO_ACCESS_TOKEN }}
          DO_APP_ID: ${{ secrets.DO_APP_ID }}
        run: |
          doctl apps list-deployments "$DO_APP_ID" --format "ID,State,Created,Updated"
