name: Get Supabase Secrets

on:
  workflow_dispatch:

jobs:
  get-secrets:
    name: Retrieve Supabase Secrets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Supabase URL
        run: |
          echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> $GITHUB_OUTPUT
        id: supabase-url

      - name: Get Supabase Anon Key
        run: |
          echo "SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}" >> $GITHUB_OUTPUT
        id: supabase-anon-key

      - name: Create .env file for frontend
        run: |
          cat > frontend/.env << EOF
          # Supabase Configuration
          VITE_SUPABASE_URL=${{ secrets.SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}
          VITE_SUPABASE_REDIRECT_URL=http://localhost:3002/auth/callback

          # API Configuration
          VITE_API_BASE_URL=http://localhost:3000
          VITE_GOOGLE_CLIENT_ID=your-google-client-id
          EOF

      - name: Display secrets (for verification)
        run: |
          echo "Supabase URL: ${{ secrets.SUPABASE_URL }}"
          echo "Supabase Anon Key: ${{ secrets.SUPABASE_ANON_KEY }}"
          echo "Environment file created in frontend/.env"
